<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class FinanceRa extends Model
{
    protected $fillable = [
        'date_f',
        'charter',
        'cargo_docum',
        'cargo',
        'corpgrpcall_centre_sales',
        'travel_agents',
        'paystack',
        'interswitch_sales',
        'web_salesteflon',
        'boh',
        'mobile_sales',
        'gtpayment',
        'gladepay',
        'excess_bag',
        'penalty',
        'domestic',
        'ibom_air',
        'zenith_bank_gulf_stream',
        'syphax',
        'aiico_travel_insurance',
        'allied_air_ltd',
        'ffv',
        'songhai_aviation',
        'green_africa',
        'avmax_aircraft_leasing_incorp',
        'middle_east_airlinesair_libran',
        'air_peace_ltd',
        'asky_aircraft_maintengr',
        'clobekadmin_charges',
        'eznis',
        'qatar',
        'aero_airline',
        'cwt_agent',
        'ezuma_jeta',
        'austamarc_intl',
        'azman',
        'gatelesis',
        'galatic',
        'galaticloc',
        'heston_mro_europe',
        'kalabash_technology_solution_ltd',
        'ng_eagle',
        'seven_star_global_hangar',
        'dana_air',
        'pieces_aviation',
        'rwandair',
        'hajj_operations',
        'sierra_leone_caa',
        'dornier_aviation_nigeria',
        'united_nigeria',
        'skycare',
        'maxair',
        'pax_service_fee',
        'travel_insurance',
        'clobekbase_fare',
        'clobekyq_surcharge',
        'just_usbase_fare',
        'just_usyq_surcharge',
        'refunddomestic_tsr',
        'refundonline_web',
        'ng_tax_5tsc',
        'qt_faan',
        'flownrevarik',
        'flownrevgalatic',
        'expired_tickets',
        'updated_at',
        'deleted_at'
    ];
}
